function [BW,maskedRGBImage] = createMaskIkiRenk(RGB)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder app. The colorspace and
%  range for each channel of the colorspace were set within the app. The
%  segmentation mask is returned in BW, and a composite of the mask and
%  original RGB images is returned in maskedRGBImage.

% Auto-generated by colorThresholder app on 15-Jan-2024
%------------------------------------------------------


% Convert RGB image to chosen color space
I = rgb2hsv(RGB);

% Define thresholds for channel 1 based on histogram settings
channel1MinMavi = 0.489;
channel1MaxMavi = 0.744;

channel1MinSari = 0.121;
channel1MaxSari = 0.170;

% Define thresholds for channel 2 based on histogram settings
channel2MinMavi = 0.243;
channel2MaxMavi = 1.000;

channel2MinSari = 0.784;
channel2MaxSari = 1.000;

% Define thresholds for channel 3 based on histogram settings
channel3MinMavi = 0.341;
channel3MaxMavi = 1.000;

channel3MinSari = 0.525;
channel3MaxSari = 1.000;

% Create mask based on chosen histogram thresholds
sliderBW = (I(:,:,1) >= channel1MinMavi ) & (I(:,:,1) <= channel1MaxMavi) & ...
    (I(:,:,2) >= channel2MinMavi ) & (I(:,:,2) <= channel2MaxMavi) & ...
    (I(:,:,3) >= channel3MinMavi ) & (I(:,:,3) <= channel3MaxMavi) | (I(:,:,1) >= channel1MinSari ) & (I(:,:,1) <= channel1MaxSari) & ...
    (I(:,:,2) >= channel2MinSari ) & (I(:,:,2) <= channel2MaxSari) & ...
    (I(:,:,3) >= channel3MinSari ) & (I(:,:,3) <= channel3MaxSari);
BW = sliderBW;

% Initialize output masked image based on input image.
maskedRGBImage = RGB;

% Set background pixels where BW is false to zero.
maskedRGBImage(repmat(~BW,[1 1 3])) = 0;

end
